{% set name = "scikit-build-core" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit_build_core-{{ version }}.tar.gz
  sha256: 1bea5ed83610b367f3446badd996f2356690548188d6d38e5b93152df311a7ae

build:
  number: 0
  skip: true  # [py<37]

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python
  run:
    - python
    - exceptiongroup             # [py<311]
    - importlib_metadata         # [py<38]
    - importlib_resources >=1.3  # [py<39]
    - packaging >=20.9
    - pyproject-metadata >=0.5
    - tomli >=1.1                # [py<311]
    - typing-extensions >=3.10   # [py<38]
  run_constrained:
    - pathspec >=0.10.1

test:
  imports:
    - scikit_build_core
  commands:
    - pip check
    - pytest -vv -m "not isolated" -k "not sdist_time_hash_set_epoch and not sdist_hash"
  source_files:
    - tests/
    - src/
    - pyproject.toml
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python-build
    - cattrs >=22.2
    - cmake
    - hatch-vcs
    - hatchling
    - make
    - ninja
    - pip
    - pybind11
    - pytest >=7.0
    - pytest-subprocess
    - rich
    - setuptools
    - virtualenv
    - wheel

about:
  home: https://github.com/scikit-build/scikit-build-core
  summary: Build backend for CMake based projects
  description: |
    Scikit-build-core is a ground-up rewrite of the classic Scikit-build, a bridge 
    between Python package build systems and CMake, the most popular compiled language 
    build system.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - src/scikit_build_core/resources/find_python/Copyright.txt
  doc_url: https://scikit-build-core.readthedocs.io/
  dev_url: https://github.com/scikit-build/scikit-build-core

extra:
  recipe-maintainers:
    - conda-forge/scikit-build
    - henryiii
    - jcfr
    - thewtex
  skip-lints:
    # uses hatchling
    - missing_wheel