{% set name = "scikit-build-core" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit_build_core-{{ version }}.tar.gz
  sha256: fa53b045c0869005a21af6aa5f6c2bd70d0a1af93e8a098ea6ee1b47e3dea183

build:
  noarch: python
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - exceptiongroup
    - importlib-metadata
    - importlib-resources >=1.3
    - packaging >=20.9
    - pathspec >=0.10.1
    - pyproject-metadata >=0.5
    - tomli >=1.1
    - typing-extensions >=3.10

test:
  imports:
    - scikit_build_core
  commands:
    - pip check
    - pytest -vv -m "not isolated" -k "not sdist_time_hash_set_epoch and not sdist_hash"
  source_files:
    - tests/
    - src/
    - pyproject.toml
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python-build
    - cattrs >=22.2
    - cmake
    - hatch-vcs
    - hatchling
    - make
    - ninja
    - pip
    - pybind11
    - pytest >=7.0
    - pytest-subprocess
    - rich
    - setuptools
    - virtualenv
    - wheel

about:
  home: https://pypi.org/project/scikit-build-core/
  summary: Build backend for CMake based projects
  license: Apache-2.0
  license_file:
    - LICENSE
    - src/scikit_build_core/resources/find_python/Copyright.txt

extra:
  recipe-maintainers:
    - conda-forge/scikit-build
    - henryiii
    - jcfr
    - thewtex
