{% set name = "scikit-build-core" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit_build_core-{{ version }}.tar.gz
  sha256: 64880e00c03e196ed2feb66676175dbbafe5fad1081edd9583c30bf6170d2fc9
  patches:                                          
    - patches/0001-register-cmake-exe-for-win.patch  # [win]
    - patches/0002-pyproject-metadata-fix.patch

build:
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [unix]
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python
  run:
    - python
    - exceptiongroup >=1.0              # [py<311]
    - importlib-metadata >=4.13         # [py<38]
    - importlib_resources >=1.3         # [py<39]
    - packaging >=21.3
    - tomli >=1.2.2                     # [py<311]
    - typing-extensions >=3.10.0        # [py<39]
    # pathspec and pyproject-metadata are actually required because
    # injected at runtime:
    # https://github.com/scikit-build/scikit-build-core/blob/d7ba004/src/scikit_build_core/build/__init__.py#L113
    - pathspec >=0.10.1
    - pyproject-metadata >=0.5

{% set tests_to_deselect = "" %}
{% set tests_to_deselect = tests_to_deselect + "--deselect=tests/test_editable_unit.py::test_navigate_editable_pkg" %}
# deselect these tests on win with symlink privileges OSError: [WinError 1314]
{% set tests_to_deselect = tests_to_deselect + " --deselect=tests/test_file_processor.py::test_on_each_with_symlink" %}           # [win]
# deselect these tests on win while build_wheel and build_editable
{% set tests_to_deselect = tests_to_deselect + " --deselect=tests/test_pyproject_extra_dirs.py::test_pep517_wheel_extra_dirs" %}  # [win]
{% set tests_to_deselect = tests_to_deselect + " --deselect=tests/test_pyproject_pep660.py::test_pep660_wheel" %}                 # [win]

{% set markers_to_skip = "isolated or network or virtualenv or setuptools or broken_on_urct" %}

{% set tests_to_skip = "sdist_time_hash_set_epoch or sdist_hash" %}

test:
  imports:
    - scikit_build_core
  commands:
    - pip check
    - set CMAKE_GENERATOR=Ninja
    # see thread https://github.com/scikit-build/scikit-build-core/issues/368
    - pytest -vv -ra --showlocals -m "not ({{ markers_to_skip }})" {{ tests_to_deselect }} -k "not ({{ tests_to_skip }})"
  source_files:
    - tests/
    - src/
    - pyproject.toml
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python-build
    - cattrs >=22.2
    - cmake
    - hatch-vcs
    - hatchling
    - make  # [unix]
    - ninja
    - numpy
    - pip
    - pathspec >=0.10.1
    - pybind11 >=2.11
    - pyproject-metadata >=0.5
    - pytest >=7.0
    - pytest-subprocess >=1.5
    - rich
    - setuptools
    - virtualenv >=20.20
    - wheel >=0.40

about:
  home: https://github.com/scikit-build/scikit-build-core
  summary: Build backend for CMake based projects
  description: |
    Scikit-build-core is a ground-up rewrite of the classic Scikit-build, a bridge 
    between Python package build systems and CMake, the most popular compiled language 
    build system.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - src/scikit_build_core/resources/find_python/Copyright.txt
  doc_url: https://scikit-build-core.readthedocs.io/
  dev_url: https://github.com/scikit-build/scikit-build-core

extra:
  recipe-maintainers:
    - conda-forge/scikit-build
    - henryiii
    - jcfr
    - thewtex
  skip-lints:
    # uses hatchling
    - missing_wheel
